// Authentication middleware

const ALLOWED_DOMAIN = process.env.ALLOWED_DOMAIN || 'brown.edu';
const BYPASS_AUTH = process.env.BYPASS_AUTH === 'true';

/**
 * Middleware to require authentication for protected routes
 * Can be bypassed in development with BYPASS_AUTH=true
 */
export function requireAuth(req, res, next) {
  // Safety check: never bypass auth in production
  if (BYPASS_AUTH && process.env.NODE_ENV === 'production') {
    console.error('SECURITY ERROR: Cannot bypass authentication in production!');
    process.exit(1);
  }

  // If auth bypass is enabled (development only), skip authentication
  if (BYPASS_AUTH) {
    console.log('⚠️  Authentication bypassed (BYPASS_AUTH=true)');
    return next();
  }

  // Check if user is authenticated
  if (req.isAuthenticated()) {
    return next();
  }

  // Not authenticated - redirect to login
  res.redirect('/login.html');
}

/**
 * Verify that the authenticated user has an allowed email domain
 * CASE-SENSITIVE: Only exact @brown.edu is allowed
 */
export function verifyDomain(email) {
  if (!email) {
    return false;
  }

  // IMPORTANT: Case-sensitive check
  // Only @brown.edu (lowercase) is valid
  // brown.edu is the ONLY domain generated by the organization
  return email.endsWith('@' + ALLOWED_DOMAIN);
}

/**
 * Check if authentication is currently bypassed
 */
export function isAuthBypassed() {
  return BYPASS_AUTH;
}
