# Google Cloud Run service configuration
# Documentation: https://cloud.google.com/run/docs/reference/yaml/v1

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gcal-lab-automation
  labels:
    cloud.googleapis.com/location: us-east1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: BETA
spec:
  template:
    metadata:
      annotations:
        # Autoscaling configuration
        autoscaling.knative.dev/minScale: '0'
        autoscaling.knative.dev/maxScale: '10'
        # Connection pooling
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      # Service account (set during deployment)
      # serviceAccountName: gcal-lab-automation-sa@PROJECT_ID.iam.gserviceaccount.com
      
      # Container configuration
      containers:
        - name: gcal-lab-automation
          # Image will be set during deployment
          # image: us-east1-docker.pkg.dev/PROJECT_ID/cloud-run-source-deploy/gcal-lab-automation:latest
          
          ports:
            - name: http1
              containerPort: 8080
          
          # Resource limits
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
          
          # Environment variables (non-sensitive)
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: '8080'
            - name: DEMO_MODE
              value: 'false'
            - name: BYPASS_AUTH
              value: 'false'
            - name: ALLOWED_DOMAIN
              value: 'brown.edu'
          
          # Startup probe
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          
          # Liveness probe
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
      
      # Timeout for requests
      timeoutSeconds: 300
